#ifndef _DEF_H_
#define _DEF_H_

#pragma warning(disable: 4244 4305)

/*#define PI 3.14159265358979323846
#define D2R(A) ((A) * PI / 180.0)
#define DEGREE2RADIANL 0.01745329251994329576L
  */
#include <windows.h>

/* Large integer types */
typedef __int64 INT64;
typedef unsigned __int64 UINT64;

/* базовый вещественный тип */
typedef double DBL;
typedef long double LDBL;
typedef float FLT;

#endif
